name: gate
base: core22
version: '9.3'
summary: A toolkit for numerical simulations in medical imaging and radiotherapy
description: |
  http://www.opengatecollaboration.org

  Gate currently supports simulations of Emission Tomography (Positron Emission Tomography - PET and Single Photon Emission Computed Tomography - SPECT), Computed Tomography (CT), Optical Imaging (Bioluminescence and Fluorescence) and Radiotherapy experiments.
  Using an easy-to-learn macro mechanism to configurate simple or highly sophisticated experimental settings, GATE now plays a key role in the design of new medical imaging devices, in the optimization of acquisition protocols and in the development and assessment of image reconstruction algorithms and correction techniques.
  It can also be used for dose calculation in radiation therapy, brachytherapy or any other application.

  This snap contains Gate bundled with Geant4 (with QT, and all optional Geant4 datasets) and ROOT.
  Simply run `Gate` or `Gate --qt` on the command line to begin using it.

  Jobsplitter tools can be accessed via `gate.gjs` and `gate.gjm`
  The split macro files will be placed in `$HOME/snap/common/.gate`

  Snaps are sandboxed applications designed to be portable and run across a wide variety of Linux systems.
  Due to the sandboxing, please ensure all your work is contained within your `$HOME` folder to be accessible.

  Please consider installing the `root-framework` snap in order to make `root` and other binaries also available on your system.
  This is not required to use the Gate snap, but may be desired by people who wish to use ROOT to analyse their output.
  Simply run `sudo snap install root-framework` or visit https://snapcraft.io/root-framework for more information.

  This product includes software developed by Members of the Geant4 Collaboration ( http://cern.ch/geant4 )

grade: stable
confinement: strict
license: LGPL-3.0
compression: lzo

parts:
  gate:
    plugin: cmake
    source: https://github.com/OpenGATE/gate.git
    source-commit: a46f46dee111ac5f2c5c3ea7ab85dd202f94ecb7 # 9.3
    cmake-parameters:
      - -DCMAKE_CXX_STANDARD=17
      - -DGATE_USE_GEANT4_UIVIS=ON
      - -DGATE_USE_TORCH=OFF
      - -DGATE_USE_OPTICAL=ON
      - -DGATE_USE_DAVIS=ON
      - -DGATE_USE_LMF=OFF
    build-environment:
      - Geant4_DIR: $CRAFT_STAGE/usr/local/lib/cmake/Geant4
      - ROOT_DIR: $CRAFT_STAGE/usr/local/cmake
      - ROOTSYS: $CRAFT_STAGE/usr/local
      - ITK_DIR: $CRAFT_STAGE/usr/local/lib/cmake
    build-packages:
      - build-essential
    stage-packages:
      - libglu1-mesa
      # QT is optional, and included with the geant4 part
    after: [libitk, geant4, root]

  jobsplitter:
    plugin: make
    source: https://github.com/OpenGATE/gate.git
    source-commit: a46f46dee111ac5f2c5c3ea7ab85dd202f94ecb7 # 9.3
    source-subdir: cluster_tools/jobsplitter
    build-environment:
      - PATH: $CRAFT_STAGE/usr/local/bin:$PATH
      - LD_LIBRARY_PATH: $CRAFT_STAGE/usr/local/lib
    build-packages:
      - build-essential
    override-pull: |
      craftctl default
      sed -i 's!/usr/local/bin!$(DESTDIR)!g' $CRAFT_PART_SRC/cluster_tools/jobsplitter/Makefile
    organize:
      gjs: usr/local/bin/gjs
    after: [gate]

  filemerger:
    plugin: make
    source: https://github.com/OpenGATE/gate.git
    source-commit: a46f46dee111ac5f2c5c3ea7ab85dd202f94ecb7 # 9.3
    source-subdir: cluster_tools/filemerger
    build-environment:
      - PATH: $CRAFT_STAGE/usr/local/bin:$PATH
      - LD_LIBRARY_PATH: $CRAFT_STAGE/usr/local/lib
    build-packages:
      - build-essential
    override-pull: |
      craftctl default
      sed -i 's!/usr/local/bin!$(DESTDIR)!g' $CRAFT_PART_SRC/cluster_tools/filemerger/Makefile
    organize:
      gjm: usr/local/bin/gjm
    after: [gate]

  libitk:
    plugin: cmake
    source: https://github.com/InsightSoftwareConsortium/ITK.git
    source-commit: 8be208ee1f04d09912523401e78ba7bb14a89d6f # 5.2.1 - avoiding 5.2.0 due to compilation bugs
    cmake-parameters:
      - -DCMAKE_CXX_STANDARD=17
      - -DMODULE_RTK=ON
      - -DBUILD_EXAMPLES=OFF
      - -DBUILD_TESTING=OFF
      - -DITKV3_COMPATIBILITY=OFF
      - -DITK_BUILD_DEFAULT_MODULES=ON
      - -DITK_WRAP_PYTHON=OFF
    build-packages:
      - build-essential
      - libxml2-dev

  geant4:
    plugin: cmake
    source: https://gitlab.cern.ch/geant4/geant4/-/archive/v11.1.0/geant4-v11.1.0.tar.gz # V11.0
    source-checksum: sha256/c4a23f2f502efeab56de43a4412b21f65c7ca1b0877b9bc1d7e845ee12edf70a
    cmake-parameters:
      - -DCMAKE_CXX_STANDARD=17
      - -DGEANT4_INSTALL_DATA=ON
      - -DGEANT4_BUILD_MULTITHREADED=OFF
      - -DGEANT4_USE_QT=ON
      - -DGEANT4_USE_RAYTRACER_X11=ON
    build-packages:
      - build-essential
      - qtbase5-dev
      - libqt5opengl5-dev
      - libexpat1-dev
      - libxmu-dev
      - libmotif-dev
      - libx11-dev
    stage-packages:
      # QT (Desktop Helpers)
      - libxkbcommon0
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - locales-all
      # QT (Snapcraft statically resolved dependencies)
      - libdouble-conversion3
      - libfreetype6
      - libgraphite2-3
      - libharfbuzz0b
      - libpcre2-32-0
      - libpng16-16
      - libqt5core5a
      - libqt5opengl5
      - libqt5widgets5
      # The rest
      - libglu1-mesa

  root:
    plugin: cmake
    source: https://github.com/root-project/root.git
    source-commit: e8464159f683e1f2843bce86d6aeac5152075451 #v6.24.06
    cmake-parameters:
      - -DCMAKE_CXX_STANDARD=17
      - -Dxrootd=OFF
      - -Dbuiltin_xrootd=OFF
    build-packages:
      - build-essential
      - libx11-dev
      - libxpm-dev
      - libxft-dev
      - libxext-dev
      - libssl-dev
      - libpcre++-dev
    stage-packages:
      - libstdc++-11-dev
      - libc6-dev
      - libglu1-mesa
      - libxft2
      - libxpm4

  extras:
    plugin: dump
    source: ./extras
    source-type: local

layout:
  /usr/include:
    bind: $SNAP/usr/include

environment:
  # Don't forget setup-sandbox.sh
  DISABLE_WAYLAND: 1
  XAUTHORITY: ${SNAP_REAL_HOME}/.Xauthority
  G4ABLADATA: $SNAP/usr/local/share/Geant4/data/G4ABLA3.1
  G4LEDATA: $SNAP/usr/local/share/Geant4/data/G4EMLOW8.2
  G4ENSDFSTATEDATA: $SNAP/usr/local/share/Geant4/data/G4ENSDFSTATE2.3
  G4INCLDATA: $SNAP/usr/local/share/Geant4/data/G4INCL1.0
  G4NEUTRONHPDATA: $SNAP/usr/local/share/Geant4/data/G4NDL4.7
  G4PARTICLEXSDATA: $SNAP/usr/local/share/Geant4/data/G4PARTICLEXS4.0
  G4PIIDATA: $SNAP/usr/local/share/Geant4/data/G4PII1.3
  G4SAIDXSDATA: $SNAP/usr/local/share/Geant4/data/G4SAIDDATA2.0
  G4LEVELGAMMADATA: $SNAP/usr/local/share/Geant4/data/PhotonEvaporation5.7
  G4RADIOACTIVEDATA: $SNAP/usr/local/share/Geant4/data/RadioactiveDecay5.6
  G4REALSURFACEDATA: $SNAP/usr/local/share/Geant4/data/RealSurface2.2
  GC_DOT_GATE_DIR: ${SNAP_USER_COMMON}
  GC_GATE_EXE_DIR: ${SNAP}/usr/local/bin
  LC_NUMERIC: C

plugs:
  home:
  opengl:
  x11:
  wayland:
  desktop:
  desktop-legacy:
  removable-media:
  gtk-2-engines:
    interface: content
    target: $SNAP/lib/gtk-2.0
    default-provider: gtk-common-themes
  gtk-2-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

apps:
  gate:
    command: usr/local/bin/Gate
    command-chain:
      - bin/setup-sandbox.sh
  gjs:
    command: usr/local/bin/gjs
    command-chain:
      - bin/setup-sandbox.sh
  gjm:
    command: usr/local/bin/gjm
    command-chain:
      - bin/setup-sandbox.sh
